"""Theme and size definitions for Client Timer."""

THEMES = {
    "Cupertino Light": {
        "text": "#0B0B0B",
        "button_text": "#0B0B0B",
        "bg": "#F0F0F5",
        "button_bg": "#FDFDFD",
        "button_active": "#43BC5C",
        "border": 0,
        "row_dragged": "#2BA54E",
        "separator": "#C7C7CC",
        "row_separator": "#DCDCDC",
        "group_header_bg": "#FDFDFD",
        "group_header_text": "#0B0B0B",
        "running_text": "#006EFB",
        "group_running_text": "#006EFB",
    },
    "Galaxy Dark": {
        "text": "#E1E7EC",
        "button_text": "#E1E7EC",
        "bg": "#010101",
        "button_bg": "#151C21",
        "button_active": "#62B3EE",
        "border": 0,
        "row_dragged": "#2A3550",
        "separator": "#2D485A",
        "row_separator": "#2E2E2E",
        "group_header_bg": "#151C21",
        "group_header_text": "#A7B5CC",
        "running_text": "#62B3EE",
        "group_running_text": "#62B3EE",
    },
    "A Way": {
        "text": "#FDF7D1",
        "button_text": "#111111",
        "bg": "#292929",
        "button_bg": "#E8B20F",
        "button_active": "#FFD75A",
        "border": 0,
        "row_dragged": "#A4860F",
        "separator": "#3A3A2A",
        "row_separator": "#26261A",
        "group_header_bg": "#1A1606",
        "group_header_text": "#FDF7D1",
        "running_text": "#FFD75A",
        "group_running_text": "#FFE47A",
    },
    "Black Herizons": {
        "text": "#EE0000",
        "button_text": "#000000",
        "bg": "#000000",
        "button_bg": "#FFFFFF",
        "button_active": "#EE0000",
        "border": 1,
        "row_dragged": "#FFB4AA",
        "separator": "#FFFFFF",
        "row_separator": "#000000",
        "group_header_bg": "#EE0000",
        "group_header_text": "#000000",
        "running_text": "#FFFFFF",
        "group_running_text": "#FFFFFF",
    },
    "Cimply Premier": {
        "text": "#333333",
        "button_text": "#023F71",
        "bg": "#E8EEF2",
        "button_bg": "#FDFDFD",
        "button_active": "#CDEBFF",
        "border": 0,
        "row_dragged": "#71767A",
        "separator": "#023F71",
        "row_separator": "#E3E3E3",
        "group_header_bg": "#009ED9",
        "group_header_text": "#151515",
        "running_text": "#0097E0",
        "group_running_text": "#FDFDFD",
    },
    "Dialpad At Dusk": {
        "text": "#FFF7FB",
        "button_text": "#FFF7FB",
        "bg": "#231735",            # deep, quiet purple
        "button_bg": "#B025A0",     # mid purple
        "button_active": "#EB2F6C", # warm sunset orange
        "border": 0,
        "row_dragged": "#54446A",
        "separator": "#4A395E",
        "row_separator": "#332543",
        "group_header_bg": "#1A1028",
        "group_header_text": "#FFF7FB",
        "running_text": "#FA593B",        # softer version of button_active
        "group_running_text": "#FA593B",
    },
    "Gray Until Further Notice": {
        "text": "#1A1A1A",
        "button_text": "#1A1A1A",
        "bg": "#D8D8D8",
        "button_bg": "#C8C8C8",
        "button_active": "#B3B3B3",
        "border": 0,
        "row_dragged": "#F1F1F1",
        "separator": "#9E9E9E",
        "row_separator": "#CECECE",
        "group_header_bg": "#B2B2B2",
        "group_header_text": "#1A1A1A",
        "running_text": "#000000",
        "group_running_text": "#000000",
    },
    "ICOMM Blues": {
        "text": "#FDFDFD",
        "button_text": "#191C22",
        "bg": "#052455",
        "button_bg": "#A7CDFD",
        "button_active": "#EFF4FD",
        "border": 0,
        "row_dragged": "#6585A8",
        "separator": "#384963",
        "row_separator": "#4F5775",
        "group_header_bg": "#0F0F36",
        "group_header_text": "#FDFDFD",
        "running_text": "#FFD700",
        "group_running_text": "#FFD700",
    },
    "Manila Memories": {
        "text": "#241E19",
        "button_text": "#241E19",
        "bg": "#E2D6C2",           # slightly more manila paper
        "button_bg": "#D2C2A8",    # manila-tinted controls
        "button_active": "#BFA680",# warm folder-tab highlight (still muted)
        "border": 0,
        "row_dragged": "#FFF3DD",
        "separator": "#BDAF9A",
        "row_separator": "#E8DDCE",
        "group_header_bg": "#D8C8AE",
        "group_header_text": "#241E19",
        "running_text": "#7B4F2F",
        "group_running_text": "#7B4F2F",
    },
    "Park In The Forest": {
        "text": "#0C130D",
        "button_text": "#0C130D",
        "bg": "#E9F2E6",          # a bit deeper / greener than before
        "button_bg": "#C9E0C5",   # darker, more “leafy”
        "button_active": "#7EC67C",  # still bright grass, slightly richer
        "border": 0,
        "row_dragged": "#B7D4B3",     # more “shadowed” grass
        "separator": "#A9BFA6",       # darker, tree-bark-ish divider
        "row_separator": "#D6E4D3",
        "group_header_bg": "#D2E3CD", # like standing under a tree shade
        "group_header_text": "#24472D",
        "running_text": "#2E7C35",    # warm, foresty green
        "group_running_text": "#205627",
    },
    "T-Magentle": {
        "text": "#E20074",
        "button_text": "#262626",
        "bg": "#FFFFFF",
        "button_bg": "#E8E8E8",
        "button_active": "#9F9F9F",
        "border": 1,
        "row_dragged": "#FFD6EC",
        "separator": "#CCCCCC",
        "row_separator": "#E0E0E0",
        "group_header_bg": "#E20074",
        "group_header_text": "#F2F2F2",
        "running_text": "#790041",
        "group_running_text": "#FFFFFF",
    }
}

FONTS = [
    "Arial",
    "Calibri",
    "Cambria",
    "Comic Sans MS",
    "Consolas",
    "Courier New",
    "Georgia",
    "Helvetica",
    "Segoe UI",
    "Tahoma",
    "Times New Roman",
    "Trebuchet MS",
    "Verdana",
]

SIZES = {
    "Microscopic": {
        "label": 9,
        "time": 7,
        "action": 6,
        "padding": 0,
        "frame_pad": 0,
        "h_spacing": 1,
        "v_spacing": 1,
    },
    "Tiny": {
        "label": 10,
        "time": 8,
        "action": 7,
        "padding": 1,
        "frame_pad": 0,
        "h_spacing": 3,
        "v_spacing": 2,
    },
    "Compact": {
        "label": 12,
        "time": 10,
        "action": 8,
        "padding": 2,
        "frame_pad": 3,
        "h_spacing": 4,
        "v_spacing": 3,
    },
    "Regular": {
        "label": 14,
        "time": 12,
        "action": 9,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 6,
        "v_spacing": 4,
    },
    "Bulky": {
        "label": 16,
        "time": 14,
        "action": 11,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 7,
        "v_spacing": 5,
    },
    "Colossal": {
        "label": 18,
        "time": 16,
        "action": 13,
        "padding": 7,
        "frame_pad": 7,
        "h_spacing": 8,
        "v_spacing": 6,
    },
    "Gargantuan": {
        "label": 22,
        "time": 20,
        "action": 18,
        "padding": 9,
        "frame_pad": 9,
        "h_spacing": 10,
        "v_spacing": 7,
    },
}
