# Theme color palettes for the UI.
#
# Key scheme: <family>[_<state>]_<role>, where role is one of:
#   _bg    a fill        _fg    text/foreground        _line   a rule or border
#
#   app_*      the window surface and default label text
#   control_*  buttons, line edits, combo boxes, list/table items, menus
#   row_*      timer rows (they inherit app_bg/app_fg; only states are listed)
#   group_*    group header rows
#   chrome_*   structural rules: footer rule, tooltip border, scrollbar, gridlines
#   toast_*    the transient notification bubble
#
# control_border_px is a wicopying dth in pixels, not a color — 0 for soft themes,
# 1 for themes with hard edges. control_line is the color that width paints in
# (and the always-on 1px edge around lists, tables and menus).
THEMES = {
    "95 Windows": {
        "app_bg":            "#C0C0C0",
        "app_fg":            "#000000",
        "app_fg_muted":      "#606060",
        "control_bg":        "#DFDFDF",
        "control_fg":        "#000000",
        "control_hover_bg":  "#B0B0B0",
        "control_hover_fg":  "#000000",
        "control_line":      "#808080",
        "control_border_px": 1,
        "row_running_fg":    "#000080",
        "row_drag_bg":       "#008080",
        "row_hover_bg":      "#D0D0D0",
        "row_line":          "#ADADAD",
        "group_bg":          "#000080",
        "group_hover_bg":    "#0000A8",
        "group_drag_bg":     "#006B6B",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFFF00",
        "group_line":        "#000080",
        "group_hover_line":  "#0000A8",
        "group_drag_line":   "#008080",
        "chrome_line":       "#808080",
        "toast_bg":          "#FFFFE1",
        "toast_fg":          "#000000",
    },
    "A Way": {
        "app_bg":            "#292929",
        "app_fg":            "#FDF7D1",
        "app_fg_muted":      "#969166",
        "control_bg":        "#383838",
        "control_fg":        "#FDF7D1",
        "control_hover_bg":  "#E8B20F",
        "control_hover_fg":  "#111111",
        "control_line":      "#4A4436",
        "control_border_px": 1,
        "row_running_fg":    "#FFD75A",
        "row_drag_bg":       "#6C590E",
        "row_hover_bg":      "#5A4A12",
        "row_line":          "#4A3D1C",
        "group_bg":          "#1C1C1C",
        "group_hover_bg":    "#34301F",
        "group_drag_bg":     "#4A3D12",
        "group_fg":          "#FDF7D1",
        "group_running_fg":  "#E8B20F",
        "group_line":        "#E8B20F",
        "group_hover_line":  "#E8B20F",
        "group_drag_line":   "#FFD75A",
        "chrome_line":       "#5A4A12",
        "toast_bg":          "#FDF7D1",
        "toast_fg":          "#1A1606",
    },
    "Billable Hours": {
        "app_bg":            "#0E1A10",
        "app_fg":            "#EAF2E2",
        "app_fg_muted":      "#748B6E",
        "control_bg":        "#17281A",
        "control_fg":        "#EAF2E2",
        "control_hover_bg":  "#CFBB4A",
        "control_hover_fg":  "#0E1A10",
        "control_line":      "#365C3B",
        "control_border_px": 1,
        "row_running_fg":    "#E8CC55",
        "row_drag_bg":       "#315C37",
        "row_hover_bg":      "#274A2C",
        "row_line":          "#1C2E1F",
        "group_bg":          "#17381D",
        "group_hover_bg":    "#205029",
        "group_drag_bg":     "#285D32",
        "group_fg":          "#F3F1D6",
        "group_running_fg":  "#E8CC55",
        "group_line":        "#2F6238",
        "group_hover_line":  "#3A7444",
        "group_drag_line":   "#4A8A55",
        "chrome_line":       "#2F5537",
        "toast_bg":          "#CFBB4A",
        "toast_fg":          "#0E1A10",
    },
    "Burning the Midnight Oil": {
        "app_bg":            "#18110B",
        "app_fg":            "#E8DDC8",
        "app_fg_muted":      "#8F7D68",

        "control_bg":        "#292118",
        "control_fg":        "#E8DDC8",
        "control_hover_bg":  "#D0A85F",
        "control_hover_fg":  "#181007",
        "control_line":      "#4C3C29",
        "control_border_px": 1,

        "row_running_fg":    "#D8B26E",
        "row_hover_bg":      "#2B231A",
        "row_drag_bg":       "#3E3121",
        "row_line":          "#272018",

        "group_bg":          "#211910",
        "group_hover_bg":    "#302318",
        "group_drag_bg":     "#47301D",
        "group_fg":          "#F0E5D1",
        "group_running_fg":  "#E1BD77",
        "group_line":        "#5B4528",
        "group_hover_line":  "#806038",
        "group_drag_line":   "#D8B26E",

        "chrome_line":       "#5E4930",

        "toast_bg":          "#D0A85F",
        "toast_fg":          "#17130F",
    },
    "Busy Signal": {
        "app_bg":            "#171311",
        "app_fg":            "#F5EEE9",
        "app_fg_muted":      "#927D72",
        "control_bg":        "#29211D",
        "control_fg":        "#F5EEE9",
        "control_hover_bg":  "#F05A28",
        "control_hover_fg":  "#160B06",
        "control_line":      "#4A3730",
        "control_border_px": 1,
        "row_running_fg":    "#FF7447",
        "row_hover_bg":      "#6B2A18",
        "row_drag_bg":       "#76200F",
        "row_line":          "#35251F",
        "group_bg":          "#B73A18",
        "group_hover_bg":    "#D5441A",
        "group_drag_bg":     "#76200F",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFE0D5",
        "group_line":        "#D64A20",
        "group_hover_line":  "#FFE0D5",
        "group_drag_line":   "#832311",
        "chrome_line":       "#5A2A1B",
        "toast_bg":          "#F05A28",
        "toast_fg":          "#160B06",
    },
    "Cold Transfer": {
        "app_bg":            "#0C1821",
        "app_fg":            "#DCEEF2",
        "app_fg_muted":      "#6D8B9A",
        "control_bg":        "#162835",
        "control_fg":        "#DCEEF2",
        "control_hover_bg":  "#23485F",
        "control_hover_fg":  "#EAF8FF",
        "control_line":      "#2C4C5F",
        "control_border_px": 1,
        "row_running_fg":    "#5ABFE7",
        "row_hover_bg":      "#234456",
        "row_drag_bg":       "#1C4E64",
        "row_line":          "#1A2C39",
        "group_bg":          "#12384E",
        "group_hover_bg":    "#184A62",
        "group_drag_bg":     "#1C5870",
        "group_fg":          "#DCEEF2",
        "group_running_fg":  "#86CFEE",
        "group_line":        "#2A5C78",
        "group_hover_line":  "#3A7898",
        "group_drag_line":   "#86CFEE",
        "chrome_line":       "#2D5670",
        "toast_bg":          "#DDF7FF",
        "toast_fg":          "#07131B",
    },
    "Copper Sunset": {
        "app_bg":            "#161F20",
        "app_fg":            "#E6DCCE",
        "app_fg_muted":      "#789093",

        "control_bg":        "#1F2D2E",
        "control_fg":        "#E6DCCE",
        "control_hover_bg":  "#509195",
        "control_hover_fg":  "#0F1516",
        "control_line":      "#335457",
        "control_border_px": 1,

        "row_running_fg":    "#E07B45",
        "row_hover_bg":      "#2D4749",
        "row_drag_bg":       "#356062",
        "row_line":          "#1D292A",

        "group_bg":          "#274042",
        "group_hover_bg":    "#315355",
        "group_drag_bg":     "#3A6668",
        "group_fg":          "#DDE8E9",
        "group_running_fg":  "#F09A5E",
        "group_line":        "#34585B",
        "group_hover_line":  "#4E7D80",
        "group_drag_line":   "#6CA5A8",

        "chrome_line":       "#3A6164",

        "toast_bg":          "#C16D4E",
        "toast_fg":          "#17100C",
    },
    "Dialpad At Dusk": {
        "app_bg":            "#231735",
        "app_fg":            "#FFF7FB",
        "app_fg_muted":      "#907D9B",
        "control_bg":        "#B025A0",
        "control_fg":        "#FFF7FB",
        "control_hover_bg":  "#EB2F6C",
        "control_hover_fg":  "#FFF7FB",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#FA593B",
        "row_hover_bg":      "#54446A",
        "row_drag_bg":       "#68437A",
        "row_line":          "#332543",
        "group_bg":          "#1A1028",
        "group_hover_bg":    "#351B4A",
        "group_drag_bg":     "#51265D",
        "group_fg":          "#FFF7FB",
        "group_running_fg":  "#FA593B",
        "group_line":        "#2E1F40",
        "group_hover_line":  "#7B347F",
        "group_drag_line":   "#B025A0",
        "chrome_line":       "#4A395E",
        "toast_bg":          "#FFC8EA",
        "toast_fg":          "#1A1028",
    },
    "Do Not Disturb": {
        "app_bg":            "#16141C",
        "app_fg":            "#FFFFFF",
        "app_fg_muted":      "#9B99AA",
        "control_bg":        "#292733",
        "control_fg":        "#F5F4F7",
        "control_hover_bg":  "#6D4AFF",
        "control_hover_fg":  "#FFFFFF",
        "control_line":      "#423D4D",
        "control_border_px": 1,
        "row_running_fg":    "#8A6EFF",
        "row_hover_bg":      "#332F42",
        "row_drag_bg":       "#40385A",
        "row_line":          "#26232E",
        "group_bg":          "#1F1D28",
        "group_hover_bg":    "#2A2438",
        "group_drag_bg":     "#352C4A",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#8A6EFF",
        "group_line":        "#423D4D",
        "group_hover_line":  "#5A4BA0",
        "group_drag_line":   "#8A6EFF",
        "chrome_line":       "#423D4D",
        "toast_bg":          "#6D4AFF",
        "toast_fg":          "#FFFFFF",
    },
    "Emergency Calls Only": {
        "app_bg":            "#0B0E11",
        "app_fg":            "#B9C2C9",
        "app_fg_muted":      "#68737C",
        "control_bg":        "#14181D",
        "control_fg":        "#B9C2C9",
        "control_hover_bg":  "#626E78",
        "control_hover_fg":  "#FFFFFF",
        "control_line":      "#262D35",
        "control_border_px": 1,
        "row_running_fg":    "#FF3B30",
        "row_hover_bg":      "#1E262F",
        "row_drag_bg":       "#2A3641",
        "row_line":          "#161A1F",
        "group_bg":          "#0F1318",
        "group_hover_bg":    "#171D24",
        "group_drag_bg":     "#202A34",
        "group_fg":          "#6E7880",
        "group_running_fg":  "#FF3B30",
        "group_line":        "#232A31",
        "group_hover_line":  "#4C5964",
        "group_drag_line":   "#B9C2C9",
        "chrome_line":       "#262D35",
        "toast_bg":          "#DCE3E9",
        "toast_fg":          "#0B0E11",
    },
    "E-Ink (Default)": {
        "app_bg":            "#FFFFFF",
        "app_fg":            "#000000",
        "app_fg_muted":      "#707070",
        "control_bg":        "#FFFFFF",
        "control_fg":        "#000000",
        "control_hover_bg":  "#888888",
        "control_hover_fg":  "#000000",
        "control_line":      "rgba(128,128,128,0.6)",
        "control_border_px": 1,
        "row_running_fg":    "#000000",
        "row_hover_bg":      "#CCCCCC",
        "row_drag_bg":       "#AAAAAA",
        "row_line":          "#DDDDDD",
        "group_bg":          "#000000",
        "group_hover_bg":    "#303030",
        "group_drag_bg":     "#555555",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#000000",
        "group_hover_line":  "#303030",
        "group_drag_line":   "#555555",
        "chrome_line":       "#000000",
        "toast_bg":          "#000000",
        "toast_fg":          "#FFFFFF",
    },
    "Galaxy Dark": {
        "app_bg":            "#010101",
        "app_fg":            "#E1E7EC",
        "app_fg_muted":      "#74818D",
        "control_bg":        "#151C21",
        "control_fg":        "#E1E7EC",
        "control_hover_bg":  "#62B3EE",
        "control_hover_fg":  "#010101",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#62B3EE",
        "row_hover_bg":      "#2A3550",
        "row_drag_bg":       "#35476A",
        "row_line":          "#2E2E2E",
        "group_bg":          "#151C21",
        "group_hover_bg":    "#203242",
        "group_drag_bg":     "#294863",
        "group_fg":          "#A7B5CC",
        "group_running_fg":  "#62B3EE",
        "group_line":        "#151C21",
        "group_hover_line":  "#203242",
        "group_drag_line":   "#294863",
        "chrome_line":       "#2D485A",
        "toast_bg":          "#1A3A55",
        "toast_fg":          "#E1E7EC",
    },
    "Gray Until Further Notice": {
        "app_bg":            "#D8D8D8",
        "app_fg":            "#1A1A1A",
        "app_fg_muted":      "#5F5F5F",
        "control_bg":        "#C8C8C8",
        "control_fg":        "#1A1A1A",
        "control_hover_bg":  "#707070",
        "control_hover_fg":  "#FFFFFF",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#000000",
        "row_hover_bg":      "#B8B8B8",
        "row_drag_bg":       "#A0A0A0",
        "row_line":          "#CECECE",
        "group_bg":          "#B2B2B2",
        "group_hover_bg":    "#9C9C9C",
        "group_drag_bg":     "#858585",
        "group_fg":          "#1A1A1A",
        "group_running_fg":  "#000000",
        "group_line":        "#B2B2B2",
        "group_hover_line":  "#9C9C9C",
        "group_drag_line":   "#858585",
        "chrome_line":       "#9E9E9E",
        "toast_bg":          "#707070",
        "toast_fg":          "#FFFFFF",
    },
    "Manila Memories": {
        "app_bg":            "#E2D6C2",
        "app_fg":            "#241E19",
        "app_fg_muted":      "#776D60",
        "control_bg":        "#D2C2A8",
        "control_fg":        "#241E19",
        "control_hover_bg":  "#BFA680",
        "control_hover_fg":  "#241E19",
        "control_line":      "rgba(196,178,148,0.6)",
        "control_border_px": 1,
        "row_running_fg":    "#7B4F2F",
        "row_hover_bg":      "#FFF3DD",
        "row_drag_bg":       "#E9CFA7",
        "row_line":          "#E8DDCE",
        "group_bg":          "#D8C8AE",
        "group_hover_bg":    "#E8D3B1",
        "group_drag_bg":     "#C9AE83",
        "group_fg":          "#4B382B",
        "group_running_fg":  "#7B4F2F",
        "group_line":        "#C4B294",
        "group_hover_line":  "#B99D73",
        "group_drag_line":   "#987650",
        "chrome_line":       "#BDAF9A",
        "toast_bg":          "#7B4F2F",
        "toast_fg":          "#FFF3DD",
    },
    "NOCturnal": {
        "app_bg":            "#000000",
        "app_fg":            "#33DD33",
        "app_fg_muted":      "#2B8F2B",
        "control_bg":        "#041504",
        "control_fg":        "#33DD33",
        "control_hover_bg":  "#33DD33",
        "control_hover_fg":  "#000000",
        "control_line":      "#1F7A1F",
        "control_border_px": 1,
        "row_running_fg":    "#88FF88",
        "row_hover_bg":      "#114411",
        "row_drag_bg":       "#196019",
        "row_line":          "#0D330D",
        "group_bg":          "#0A2A0A",
        "group_hover_bg":    "#0F3A0F",
        "group_drag_bg":     "#165316",
        "group_fg":          "#33DD33",
        "group_running_fg":  "#88FF88",
        "group_line":        "#33DD33",
        "group_hover_line":  "#55E055",
        "group_drag_line":   "#88FF88",
        "chrome_line":       "#1F7A1F",
        "toast_bg":          "#33DD33",
        "toast_fg":          "#000000",
    },
    "Out Of Office": {
        "app_bg":            "#F3EFE5",
        "app_fg":            "#2C3A36",
        "app_fg_muted":      "#7D725F",
        "control_bg":        "#E6DCC5",
        "control_fg":        "#2C3A36",
        "control_hover_bg":  "#72BBB4",
        "control_hover_fg":  "#16302F",
        "control_line":      "#D9CBAF",
        "control_border_px": 0,
        "row_running_fg":    "#0E8C87",
        "row_hover_bg":      "#DCEAE0",
        "row_drag_bg":       "#BEDDD5",
        "row_line":          "#E5DAC2",
        "group_bg":          "#A4CEC5",
        "group_hover_bg":    "#95C5BB",
        "group_drag_bg":     "#82B7AC",
        "group_fg":          "#24443F",
        "group_running_fg":  "#075A57",
        "group_line":        "#0E8C87",
        "group_hover_line":  "#087A76",
        "group_drag_line":   "#075E5A",
        "chrome_line":       "#D2C7B1",
        "toast_bg":          "#0E8C87",
        "toast_fg":          "#F7F1E3",
    },
    "Park In The Forest": {
        "app_bg":            "#E9F2E6",
        "app_fg":            "#0C130D",
        "app_fg_muted":      "#687A67",
        "control_bg":        "#C9E0C5",
        "control_fg":        "#0C130D",
        "control_hover_bg":  "#7EC67C",
        "control_hover_fg":  "#0C130D",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#2E7C35",
        "row_hover_bg":      "#B7D4B3",
        "row_drag_bg":       "#99C196",
        "row_line":          "#D6E4D3",
        "group_bg":          "#D2E3CD",
        "group_hover_bg":    "#BDD6B8",
        "group_drag_bg":     "#8FB98C",
        "group_fg":          "#24472D",
        "group_running_fg":  "#205627",
        "group_line":        "#24472D",
        "group_hover_line":  "#2D6037",
        "group_drag_line":   "#2E7C35",
        "chrome_line":       "#A9BFA6",
        "toast_bg":          "#2E7C35",
        "toast_fg":          "#FFFFFF",
    },
    "Per My Last Email": {
        "app_bg":            "#000000",
        "app_fg":            "#F5F5F5",
        "app_fg_muted":      "#7E7E7E",
        "control_bg":        "#1C1C1C",
        "control_fg":        "#F5F5F5",
        "control_hover_bg":  "#FFE000",
        "control_hover_fg":  "#000000",
        "control_line":      "#3A3A3A",
        "control_border_px": 1,
        "row_running_fg":    "#FFE000",
        "row_hover_bg":      "#665A00",
        "row_drag_bg":       "#8A7900",
        "row_line":          "#2A2A2A",
        "group_bg":          "#FFE000",
        "group_hover_bg":    "#BDA800",
        "group_drag_bg":     "#8A7900",
        "group_fg":          "#000000",
        "group_running_fg":  "#000000",
        "group_line":        "#FFE000",
        "group_hover_line":  "#BDA800",
        "group_drag_line":   "#8A7900",
        "chrome_line":       "#FFE000",
        "toast_bg":          "#FFE000",
        "toast_fg":          "#000000",
    },
    "Single Pane of Glass": {
        "app_bg":            "#E8EEF2",
        "app_fg":            "#333333",
        "app_fg_muted":      "#606D76",
        "control_bg":        "#FDFDFD",
        "control_fg":        "#023F71",
        "control_hover_bg":  "#8FD2F3",
        "control_hover_fg":  "#023F71",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#0097E0",
        "row_hover_bg":      "#CEDFE9",
        "row_drag_bg":       "#A9C9DC",
        "row_line":          "#E3E3E3",
        "group_bg":          "#009ED9",
        "group_hover_bg":    "#008FC5",
        "group_drag_bg":     "#0088BC",
        "group_fg":          "#000000",
        "group_running_fg":  "#000000",
        "group_line":        "#009ED9",
        "group_hover_line":  "#008FC5",
        "group_drag_line":   "#0088BC",
        "chrome_line":       "#023F71",
        "toast_bg":          "#023F71",
        "toast_fg":          "#FDFDFD",
    },
    "Telecomm Blues": {
        "app_bg":            "#052455",
        "app_fg":            "#FDFDFD",
        "app_fg_muted":      "#7C8CAB",
        "control_bg":        "#A7CDFD",
        "control_fg":        "#191C22",
        "control_hover_bg":  "#EFF4FD",
        "control_hover_fg":  "#191C22",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#FFD700",
        "row_hover_bg":      "#466A94",
        "row_drag_bg":       "#5C82AD",
        "row_line":          "#4F5775",
        "group_bg":          "#0F0F36",
        "group_hover_bg":    "#292944",
        "group_drag_bg":     "#3A3A5C",
        "group_fg":          "#FDFDFD",
        "group_running_fg":  "#FFD700",
        "group_line":        "#0F0F36",
        "group_hover_line":  "#3C3C59",
        "group_drag_line":   "#3A3A5C",
        "chrome_line":       "#384963",
        "toast_bg":          "#E5EAFF",
        "toast_fg":          "#191C22",
    },
    "T-Magenta": {
        "app_bg":            "#FFFFFF",
        "app_fg":            "#E20074",
        "app_fg_muted":      "#737373",
        "control_bg":        "#E8E8E8",
        "control_fg":        "#262626",
        "control_hover_bg":  "#790041",
        "control_hover_fg":  "#FFFFFF",
        "control_line":      "#CCCCCC",
        "control_border_px": 1,
        "row_running_fg":    "#790041",
        "row_hover_bg":      "#FFE6F3",
        "row_drag_bg":       "#FFD6EC",
        "row_line":          "#E0E0E0",
        "group_bg":          "#E20074",
        "group_hover_bg":    "#C40065",
        "group_drag_bg":     "#860043",
        "group_fg":          "#F2F2F2",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#E20074",
        "group_hover_line":  "#C40065",
        "group_drag_line":   "#860043",
        "chrome_line":       "#CCCCCC",
        "toast_bg":          "#860043",
        "toast_fg":          "#FFFFFF",
    },
    "Your Call Is Important to Us": {
        "app_bg":            "#F3F0FA",
        "app_fg":            "#302A40",
        "app_fg_muted":      "#7D7389",
        "control_bg":        "#E5DDF2",
        "control_fg":        "#302A40",
        "control_hover_bg":  "#AA8DCE",
        "control_hover_fg":  "#241C35",
        "control_line":      "#D1C6E2",
        "control_border_px": 0,
        "row_running_fg":    "#7053A5",
        "row_hover_bg":      "#D7CAEB",
        "row_drag_bg":       "#C3AEDD",
        "row_line":          "#E7E0F0",
        "group_bg":          "#D9CCEC",
        "group_hover_bg":    "#C9B8E0",
        "group_drag_bg":     "#BBA4D8",
        "group_fg":          "#302A40",
        "group_running_fg":  "#5B3F91",
        "group_line":        "#CBBCE1",
        "group_hover_line":  "#B7A3D0",
        "group_drag_line":   "#9B80C1",
        "chrome_line":       "#C5B8D8",
        "toast_bg":          "#7053A5",
        "toast_fg":          "#FFFFFF",
    }
}
