# Theme color palettes for the UI.
#
# Key scheme: <family>[_<state>]_<role>, where role is one of:
#   _bg    a fill        _fg    text/foreground        _line   a rule or border
#
#   app_*      the window surface and default label text
#   control_*  buttons, line edits, combo boxes, list/table items, menus
#   row_*      timer rows (they inherit app_bg/app_fg; only states are listed)
#   group_*    group header rows
#   chrome_*   structural rules: footer rule, tooltip border, scrollbar, gridlines
#   toast_*    the transient notification bubble
#
# control_border_px is a width in pixels, not a color — 0 for soft themes,
# 1 for themes with hard edges. control_line is the color that width paints in
# (and the always-on 1px edge around lists, tables and menus).
THEMES = {
    "A Way": {
        "app_bg":            "#292929",
        "app_fg":            "#FDF7D1",
        "app_fg_muted":      "#706D4A",
        "control_bg":        "#E8B20F",
        "control_fg":        "#111111",
        "control_hover_bg":  "#FFD75A",
        "control_hover_fg":  "#111111",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#FFD75A",
        "row_drag_bg":       "#A4860F",
        "row_line":          "#4A3D1C",
        "group_bg":          "#1A1606",
        "group_fg":          "#FDF7D1",
        "group_running_fg":  "#FFE47A",
        "group_line":        "#1A1606",
        "chrome_line":       "#1A1606",
        "toast_bg":          "#FDF7D1",
        "toast_fg":          "#1A1606",
    },
    "Black Herizons": {
        "app_bg":            "#000000",
        "app_fg":            "#F5F5F5",
        "app_fg_muted":      "#666666",
        "control_bg":        "#FFFFFF",
        "control_fg":        "#000000",
        "control_hover_bg":  "#EE0000",
        "control_hover_fg":  "#F5F5F5",
        "control_line":      "#929292",
        "control_border_px": 1,
        "row_running_fg":    "#EE0000",
        "row_drag_bg":       "#7A0000",
        "row_line":          "#2A2A2A",
        "group_bg":          "#EE0000",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#EE0000",
        "chrome_line":       "#FFFFFF",
        "toast_bg":          "#EE0000",
        "toast_fg":          "#FFFFFF",
    },
    "Single Pane of Glass": {
        "app_bg":            "#E8EEF2",
        "app_fg":            "#333333",
        "app_fg_muted":      "#999999",
        "control_bg":        "#FDFDFD",
        "control_fg":        "#023F71",
        "control_hover_bg":  "#CDEBFF",
        "control_hover_fg":  "#023F71",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#0097E0",
        "row_drag_bg":       "#71767A",
        "row_line":          "#E3E3E3",
        "group_bg":          "#009ED9",
        "group_fg":          "#151515",
        "group_running_fg":  "#151515",
        "group_line":        "#009ED9",
        "chrome_line":       "#023F71",
        "toast_bg":          "#023F71",
        "toast_fg":          "#FDFDFD",
    },
    "Dialpad At Dusk": {
        "app_bg":            "#231735",
        "app_fg":            "#FFF7FB",
        "app_fg_muted":      "#6B5A75",
        "control_bg":        "#B025A0",
        "control_fg":        "#FFF7FB",
        "control_hover_bg":  "#EB2F6C",
        "control_hover_fg":  "#FFF7FB",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#FA593B",
        "row_drag_bg":       "#54446A",
        "row_line":          "#332543",
        "group_bg":          "#1A1028",
        "group_fg":          "#FFF7FB",
        "group_running_fg":  "#FA593B",
        "group_line":        "#2E1F40",
        "chrome_line":       "#4A395E",
        "toast_bg":          "#FFC8EA",
        "toast_fg":          "#1A1028",
    },
    "E-Ink (Default)": {
        "app_bg":            "#FFFFFF",
        "app_fg":            "#000000",
        "app_fg_muted":      "#999999",
        "control_bg":        "#FFFFFF",
        "control_fg":        "#000000",
        "control_hover_bg":  "#DDDDDD",
        "control_hover_fg":  "#000000",
        "control_line":      "rgba(128,128,128,0.6)",
        "control_border_px": 1,
        "row_running_fg":    "#000000",
        "row_drag_bg":       "#CCCCCC",
        "row_line":          "#DDDDDD",
        "group_bg":          "#000000",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#000000",
        "chrome_line":       "#000000",
        "toast_bg":          "#000000",
        "toast_fg":          "#FFFFFF",
    },
    "Galaxy Dark": {
        "app_bg":            "#010101",
        "app_fg":            "#E1E7EC",
        "app_fg_muted":      "#555F6A",
        "control_bg":        "#151C21",
        "control_fg":        "#E1E7EC",
        "control_hover_bg":  "#62B3EE",
        "control_hover_fg":  "#010101",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#62B3EE",
        "row_drag_bg":       "#2A3550",
        "row_line":          "#2E2E2E",
        "group_bg":          "#151C21",
        "group_fg":          "#A7B5CC",
        "group_running_fg":  "#62B3EE",
        "group_line":        "#151C21",
        "chrome_line":       "#2D485A",
        "toast_bg":          "#1A3A55",
        "toast_fg":          "#E1E7EC",
    },
    "Gray Until Further Notice": {
        "app_bg":            "#D8D8D8",
        "app_fg":            "#1A1A1A",
        "app_fg_muted":      "#909090",
        "control_bg":        "#C8C8C8",
        "control_fg":        "#1A1A1A",
        "control_hover_bg":  "#B3B3B3",
        "control_hover_fg":  "#1A1A1A",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#000000",
        "row_drag_bg":       "#F1F1F1",
        "row_line":          "#CECECE",
        "group_bg":          "#B2B2B2",
        "group_fg":          "#1A1A1A",
        "group_running_fg":  "#000000",
        "group_line":        "#B2B2B2",
        "chrome_line":       "#9E9E9E",
        "toast_bg":          "#707070",
        "toast_fg":          "#FFFFFF",
    },
    "Hazard Stripe": {
        "app_bg":            "#000000",
        "app_fg":            "#F5F5F5",
        "app_fg_muted":      "#666666",
        "control_bg":        "#1C1C1C",
        "control_fg":        "#F5F5F5",
        "control_hover_bg":  "#FFE000",
        "control_hover_fg":  "#000000",
        "control_line":      "#3A3A3A",
        "control_border_px": 1,
        "row_running_fg":    "#FFE000",
        "row_drag_bg":       "#665A00",
        "row_line":          "#2A2A2A",
        "group_bg":          "#FFE000",
        "group_fg":          "#000000",
        "group_running_fg":  "#000000",
        "group_line":        "#FFE000",
        "chrome_line":       "#FFE000",
        "toast_bg":          "#FFE000",
        "toast_fg":          "#000000",
    },
    "Telecomm Blues": {
        "app_bg":            "#052455",
        "app_fg":            "#FDFDFD",
        "app_fg_muted":      "#5A6888",
        "control_bg":        "#A7CDFD",
        "control_fg":        "#191C22",
        "control_hover_bg":  "#EFF4FD",
        "control_hover_fg":  "#191C22",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#FFD700",
        "row_drag_bg":       "#6585A8",
        "row_line":          "#4F5775",
        "group_bg":          "#0F0F36",
        "group_fg":          "#FDFDFD",
        "group_running_fg":  "#FFD700",
        "group_line":        "#0F0F36",
        "chrome_line":       "#384963",
        "toast_bg":          "#E5EAFF",
        "toast_fg":          "#191C22",
    },
    "Manila Memories": {
        "app_bg":            "#E2D6C2",
        "app_fg":            "#241E19",
        "app_fg_muted":      "#A09585",
        "control_bg":        "#D2C2A8",
        "control_fg":        "#241E19",
        "control_hover_bg":  "#BFA680",
        "control_hover_fg":  "#241E19",
        "control_line":      "rgba(196,178,148,0.6)",
        "control_border_px": 1,
        "row_running_fg":    "#7B4F2F",
        "row_drag_bg":       "#FFF3DD",
        "row_line":          "#E8DDCE",
        "group_bg":          "#D8C8AE",
        "group_fg":          "#241E19",
        "group_running_fg":  "#7B4F2F",
        "group_line":        "#C4B294",
        "chrome_line":       "#BDAF9A",
        "toast_bg":          "#7B4F2F",
        "toast_fg":          "#FFF3DD",
    },
    "Muted Dev-Dark": {
        "app_bg":            "#2E3440",
        "app_fg":            "#D8DEE9",
        "app_fg_muted":      "#616E88",
        "control_bg":        "#3B4252",
        "control_fg":        "#E5E9F0",
        "control_hover_bg":  "#4C566A",
        "control_hover_fg":  "#E5E9F0",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#88C0D0",
        "row_drag_bg":       "#434C5E",
        "row_line":          "#3B4252",
        "group_bg":          "#3B4252",
        "group_fg":          "#88C0D0",
        "group_running_fg":  "#88C0D0",
        "group_line":        "#434C5E",
        "chrome_line":       "#4C566A",
        "toast_bg":          "#88C0D0",
        "toast_fg":          "#2E3440",
    },
    "NOCturnal": {
        "app_bg":            "#000000",
        "app_fg":            "#33DD33",
        "app_fg_muted":      "#1A6B1A",
        "control_bg":        "#041504",
        "control_fg":        "#33DD33",
        "control_hover_bg":  "#0F3D0F",
        "control_hover_fg":  "#33DD33",
        "control_line":      "#1F7A1F",
        "control_border_px": 1,
        "row_running_fg":    "#88FF88",
        "row_drag_bg":       "#114411",
        "row_line":          "#0D330D",
        "group_bg":          "#0A2A0A",
        "group_fg":          "#33DD33",
        "group_running_fg":  "#88FF88",
        "group_line":        "#33DD33",
        "chrome_line":       "#1F7A1F",
        "toast_bg":          "#33DD33",
        "toast_fg":          "#000000",
    },
    "Park In The Forest": {
        "app_bg":            "#E9F2E6",
        "app_fg":            "#0C130D",
        "app_fg_muted":      "#8A9A88",
        "control_bg":        "#C9E0C5",
        "control_fg":        "#0C130D",
        "control_hover_bg":  "#7EC67C",
        "control_hover_fg":  "#0C130D",
        "control_line":      "rgba(128,128,128,0.4)",
        "control_border_px": 0,
        "row_running_fg":    "#2E7C35",
        "row_drag_bg":       "#B7D4B3",
        "row_line":          "#D6E4D3",
        "group_bg":          "#D2E3CD",
        "group_fg":          "#24472D",
        "group_running_fg":  "#205627",
        "group_line":        "#24472D",
        "chrome_line":       "#A9BFA6",
        "toast_bg":          "#2E7C35",
        "toast_fg":          "#FFFFFF",
    },
    "Ring Around The Rosie": {
        "app_bg":            "#FCF5F4",
        "app_fg":            "#4F4046",
        "app_fg_muted":      "#BCACB1",
        "control_bg":        "#F7E9EA",
        "control_fg":        "#4F4046",
        "control_hover_bg":  "#EDD5DA",
        "control_hover_fg":  "#3E3036",
        "control_line":      "#E4D0D4",
        "control_border_px": 0,
        "row_running_fg":    "#C05C7E",
        "row_drag_bg":       "#F4E4EE",
        "row_line":          "#F0E2E3",
        "group_bg":          "#EEDCE0",
        "group_fg":          "#4F4046",
        "group_running_fg":  "#AE4E71",
        "group_line":        "#DFC7CD",
        "chrome_line":       "#D8BFC5",
        "toast_bg":          "#C05C7E",
        "toast_fg":          "#FFF6F8",
    },
    "T-Magentle": {
        "app_bg":            "#FFFFFF",
        "app_fg":            "#E20074",
        "app_fg_muted":      "#AAAAAA",
        "control_bg":        "#E8E8E8",
        "control_fg":        "#262626",
        "control_hover_bg":  "#9F9F9F",
        "control_hover_fg":  "#262626",
        "control_line":      "#CCCCCC",
        "control_border_px": 1,
        "row_running_fg":    "#790041",
        "row_drag_bg":       "#FFD6EC",
        "row_line":          "#E0E0E0",
        "group_bg":          "#E20074",
        "group_fg":          "#F2F2F2",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#E20074",
        "chrome_line":       "#CCCCCC",
        "toast_bg":          "#860043",
        "toast_fg":          "#FFFFFF",
    },
    "Windows 95": {
        "app_bg":            "#C0C0C0",
        "app_fg":            "#000000",
        "app_fg_muted":      "#808080",
        "control_bg":        "#DFDFDF",
        "control_fg":        "#000000",
        "control_hover_bg":  "#B0B0B0",
        "control_hover_fg":  "#000000",
        "control_line":      "#808080",
        "control_border_px": 1,
        "row_running_fg":    "#000080",
        "row_drag_bg":       "#008080",
        "row_line":          "#ADADAD",
        "group_bg":          "#000080",
        "group_fg":          "#FFFFFF",
        "group_running_fg":  "#FFFFFF",
        "group_line":        "#000080",
        "chrome_line":       "#808080",
        "toast_bg":          "#FFFFE1",
        "toast_fg":          "#000000",
    },
}
