# Size presets for the UI.
#
# btn_pad / name_pad / row_pad are WIDTH knobs, added because three pixel
# constants used to bypass this table entirely: a flat +20 on the toggle
# button, +4 on the name column, and a 3px inset on group rows. Everything
# else halved as the preset shrank; those did not, so the fixed share of a
# row went from ~11% at Gargantuan to ~24% at Microscopic. Small presets
# ended up claiming width they had no text to fill, which made Compact read
# as LESS dense than Regular.
#
# Regular holds the original 20/4/3 exactly, so the default preset is
# unchanged. The rest scale with the label font, trimmed at the small end.
SIZES = {
    "Microscopic": {
        "btn_pad": 18,
        "name_pad": 2,
        "row_pad": 1,
        "label": 9,
        "time": 7,
        "action": 6,
        "padding": 0,
        "frame_pad": 0,
        "h_spacing": 1,
        "v_spacing": 1,
        "line_gap": 1,
        "footer_gap": 1,
        "scrollbar_gap": 1,
        "footer_line_gap": 1,
    },
    "Tiny": {
        "btn_pad": 18,
        "name_pad": 2,
        "row_pad": 2,
        "label": 10,
        "time": 8,
        "action": 7,
        "padding": 1,
        "frame_pad": 0,
        "h_spacing": 3,
        "v_spacing": 2,
        "line_gap": 2,
        "footer_gap": 2,
        "scrollbar_gap": 2,
        "footer_line_gap": 2,
    },
    "Compact": {
        "btn_pad": 18,
        "name_pad": 3,
        "row_pad": 2,
        "label": 12,
        "time": 10,
        "action": 8,
        "padding": 2,
        "frame_pad": 3,
        "h_spacing": 4,
        "v_spacing": 3,
        "line_gap": 4,
        "footer_gap": 3,
        "scrollbar_gap": 3,
        "footer_line_gap": 3,
    },
    "Regular": {
        "btn_pad": 20,
        "name_pad": 4,
        "row_pad": 3,
        "label": 14,
        "time": 12,
        "action": 9,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 6,
        "v_spacing": 4,
        "line_gap": 4,
        "footer_gap": 4,
        "scrollbar_gap": 4,
        "footer_line_gap": 4,
    },
    "Bulky": {
        "btn_pad": 23,
        "name_pad": 5,
        "row_pad": 3,
        "label": 16,
        "time": 14,
        "action": 11,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 7,
        "v_spacing": 5,
        "line_gap": 5,
        "footer_gap": 5,
        "scrollbar_gap": 5,
        "footer_line_gap": 5,
    },
    "Colossal": {
        "btn_pad": 26,
        "name_pad": 5,
        "row_pad": 4,
        "label": 18,
        "time": 16,
        "action": 13,
        "padding": 7,
        "frame_pad": 7,
        "h_spacing": 8,
        "v_spacing": 6,
        "line_gap": 6,
        "footer_gap": 6,
        "scrollbar_gap": 6,
        "footer_line_gap": 6,
    },
    "Gargantuan": {
        "btn_pad": 32,
        "name_pad": 7,
        "row_pad": 5,
        "label": 22,
        "time": 20,
        "action": 18,
        "padding": 9,
        "frame_pad": 9,
        "h_spacing": 10,
        "v_spacing": 7,
        "line_gap": 8,
        "footer_gap": 7,
        "scrollbar_gap": 8,
        "footer_line_gap": 7,
    },
}
