# Size presets for the UI.
SIZES = {
    "Microscopic": {
        "label": 9,
        "time": 7,
        "action": 6,
        "padding": 0,
        "frame_pad": 0,
        "h_spacing": 1,
        "v_spacing": 1,
        "line_gap": 1,
        "footer_gap": 1,
        "scrollbar_gap": 1,
        "footer_line_gap": 1,
    },
    "Tiny": {
        "label": 10,
        "time": 8,
        "action": 7,
        "padding": 1,
        "frame_pad": 0,
        "h_spacing": 3,
        "v_spacing": 2,
        "line_gap": 2,
        "footer_gap": 2,
        "scrollbar_gap": 2,
        "footer_line_gap": 2,
    },
    "Compact": {
        "label": 12,
        "time": 10,
        "action": 8,
        "padding": 2,
        "frame_pad": 3,
        "h_spacing": 4,
        "v_spacing": 3,
        "line_gap": 4,
        "footer_gap": 3,
        "scrollbar_gap": 3,
        "footer_line_gap": 3,
    },
    "Regular": {
        "label": 14,
        "time": 12,
        "action": 9,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 6,
        "v_spacing": 4,
        "line_gap": 4,
        "footer_gap": 4,
        "scrollbar_gap": 4,
        "footer_line_gap": 4,
    },
    "Bulky": {
        "label": 16,
        "time": 14,
        "action": 11,
        "padding": 5,
        "frame_pad": 5,
        "h_spacing": 7,
        "v_spacing": 5,
        "line_gap": 5,
        "footer_gap": 5,
        "scrollbar_gap": 5,
        "footer_line_gap": 5,
    },
    "Colossal": {
        "label": 18,
        "time": 16,
        "action": 13,
        "padding": 7,
        "frame_pad": 7,
        "h_spacing": 8,
        "v_spacing": 6,
        "line_gap": 6,
        "footer_gap": 6,
        "scrollbar_gap": 6,
        "footer_line_gap": 6,
    },
    "Gargantuan": {
        "label": 22,
        "time": 20,
        "action": 18,
        "padding": 9,
        "frame_pad": 9,
        "h_spacing": 10,
        "v_spacing": 7,
        "line_gap": 8,
        "footer_gap": 7,
        "scrollbar_gap": 8,
        "footer_line_gap": 7,
    },
}
