from .colors import THEMES

# Stylesheet generator for main windows.
def build_stylesheet(theme_name):
    """Build a Qt stylesheet string from a theme name."""
    t = THEMES.get(theme_name, THEMES["E-Ink (Default)"])
    act_fg = t["control_hover_fg"]
    line_c = t["control_line"]
    return (
        f"QMainWindow, QDialog, QWidget {{ background-color: {t['app_bg']}; }}"
        f"QLabel {{ color: {t['app_fg']}; background: transparent; }}"
        f"QPushButton {{"
        f"  color: {t['control_fg']};"
        f"  background-color: {t['control_bg']};"
        f"  border: {t['control_border_px']}px solid {line_c};"
        f"  padding: 4px 8px;"
        f"}}"
        f"QPushButton:hover, QPushButton:pressed {{"
        f"  color: {act_fg};"
        f"  background-color: {t['control_hover_bg']};"
        f"}}"
        f"QPushButton:disabled {{"
        f"  color: {t['app_fg_muted']};"
        f"  background-color: {t['app_bg']};"
        f"}}"
        f"QLineEdit {{"
        f"  color: {t['control_fg']};"
        f"  background-color: {t['control_bg']};"
        f"  border: {t['control_border_px']}px solid {line_c};"
        f"  padding: 3px 5px;"
        f"}}"
        f"QComboBox {{"
        f"  color: {t['control_fg']};"
        f"  background-color: {t['control_bg']};"
        f"  border: {t['control_border_px']}px solid {line_c};"
        f"  padding: 3px 5px;"
        f"}}"
        f"QComboBox QAbstractItemView {{"
        f"  color: {t['control_fg']};"
        f"  background-color: {t['control_bg']};"
        f"  selection-background-color: {t['control_hover_bg']};"
        f"  selection-color: {act_fg};"
        f"}}"
        f"QSpinBox, QTimeEdit {{"
        f"  color: {t['control_fg']};"
        f"  background-color: {t['control_bg']};"
        f"  border: {t['control_border_px']}px solid {line_c};"
        f"  padding: 3px 20px 3px 5px;"
        f"}}"
        f"QListWidget {{"
        f"  background-color: {t['control_bg']};"
        f"  border: 1px solid {line_c};"
        f"  outline: none;"
        f"}}"
        f"QListWidget::item {{"
        f"  color: {t['control_fg']};"
        f"  padding: 8px 12px;"
        f"}}"
        f"QListWidget::item:selected {{"
        f"  background-color: {t['control_hover_bg']};"
        f"  color: {act_fg};"
        f"}}"
        f"QToolTip {{"
        f"  background-color: {t['app_bg']};"
        f"  color: {t['app_fg']};"
        f"  border: 1px solid {t['chrome_line']};"
        f"  padding: 4px 8px;"
        f"}}"
        f"QScrollBar:vertical {{"
        f"  background: {t['app_bg']};"
        f"  width: 10px;"
        f"  margin: 0;"
        f"}}"
        f"QScrollBar::handle:vertical {{"
        f"  background: {t['chrome_line']};"
        f"  min-height: 20px;"
        f"  border-radius: 5px;"
        f"}}"
        f"QScrollBar::handle:vertical:hover {{"
        f"  background: {t['control_hover_bg']};"
        f"}}"
        f"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{"
        f"  height: 0;"
        f"}}"
        f"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{"
        f"  background: none;"
        f"}}"
        f"QScrollBar:horizontal {{"
        f"  background: {t['app_bg']};"
        f"  height: 10px;"
        f"  margin: 0;"
        f"}}"
        f"QScrollBar::handle:horizontal {{"
        f"  background: {t['chrome_line']};"
        f"  min-width: 20px;"
        f"  border-radius: 5px;"
        f"}}"
        f"QScrollBar::handle:horizontal:hover {{"
        f"  background: {t['control_hover_bg']};"
        f"}}"
        f"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{"
        f"  width: 0;"
        f"}}"
        f"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{"
        f"  background: none;"
        f"}}"
        f"QTableWidget {{"
        f"  background-color: {t['control_bg']};"
        f"  color: {t['control_fg']};"
        f"  gridline-color: {t['chrome_line']};"
        f"  border: 1px solid {line_c};"
        f"}}"
        f"QTableWidget::item:selected {{"
        f"  background-color: {t['control_hover_bg']};"
        f"  color: {act_fg};"
        f"}}"
        f"QHeaderView::section {{"
        f"  background-color: {t['app_bg']};"
        f"  color: {t['app_fg']};"
        f"  border: none;"
        f"  border-bottom: 1px solid {t['chrome_line']};"
        f"  padding: 4px;"
        f"}}"
        f"QFrame#settingsSep {{"
        f"  background: {t['chrome_line']};"
        f"  border: none;"
        f"  max-height: 2px;"
        f"}}"
    )

# Stylesheet generator for context menus.
def build_menu_stylesheet(theme_name):
    """Build a Qt stylesheet for context menus."""
    t = THEMES.get(theme_name, THEMES["E-Ink (Default)"])
    act_fg = t["control_hover_fg"]
    line_c = t["control_line"]
    return (
        f"QMenu {{ background-color: {t['control_bg']}; color: {t['control_fg']};"
        f"  border: 1px solid {line_c}; }}"
        f"QMenu::item {{ padding: 4px 20px; }}"
        f"QMenu::item:selected {{ background-color: {t['control_hover_bg']};"
        f"  color: {act_fg}; }}"
        f"QMenu::separator {{ height: 1px; background: rgba(128,128,128,0.4);"
        f"  margin: 4px 0px; }}"
    )
